/* Generated By:JJTree: Do not edit this line. ASTDecimal.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package rei;

public
class ASTDecimal extends SimpleNode {
  public ASTDecimal(int id) {
    super(id);
  }

  public ASTDecimal(SimpleCalculatorParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SimpleCalculatorParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=53774d65316de979246ddde16d1218f3 (do not edit this line) */
