/* Generated By:JJTree: Do not edit this line. ASTMulExpr.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package rei;

public
class ASTMulExpr extends SimpleNode {
  public ASTMulExpr(int id) {
    super(id);
  }

  public ASTMulExpr(SimpleCalculatorParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SimpleCalculatorParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=342835e2cf4a417dc0cde964c4a1f4c8 (do not edit this line) */
