/* Generated By:JavaCC: Do not edit this line. SimpleCalculatorParserDefaultVisitor.java Version 7.0.12 */
package rei;

public class SimpleCalculatorParserDefaultVisitor implements SimpleCalculatorParserVisitor{
  public Object defaultVisit(SimpleNode node, Object data){
    node.childrenAccept(this, data);
    return data;
  }
  public Object visit(SimpleNode node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTRoot node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTExpr node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTAddExpr node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTMulExpr node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTUnaryExpr node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTDecimal node, Object data){
    return defaultVisit(node, data);
  }
}
/* JavaCC - OriginalChecksum=22203de4961852d96a9ccbc26d4a27ef (do not edit this line) */
