/* Generated By:JJTree&JavaCC: Do not edit this line. SimpleCalculatorParserConstants.java */
package rei;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SimpleCalculatorParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ADD_OP = 4;
  /** RegularExpression Id. */
  int MUL_OP = 5;
  /** RegularExpression Id. */
  int OPEN_BRACKET = 6;
  /** RegularExpression Id. */
  int CLOSE_BRACKET = 7;
  /** RegularExpression Id. */
  int DECIMAL = 8;
  /** RegularExpression Id. */
  int DIGIT = 9;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "<ADD_OP>",
    "<MUL_OP>",
    "\"(\"",
    "\")\"",
    "<DECIMAL>",
    "<DIGIT>",
    "\"\\n\"",
  };

}
