/* Generated By:JavaCC: Do not edit this line. SimpleCalculatorParserTreeConstants.java Version 7.0.12 */
package rei;

public interface SimpleCalculatorParserTreeConstants
{
  public int JJTROOT = 0;
  public int JJTEXPR = 1;
  public int JJTADDEXPR = 2;
  public int JJTMULEXPR = 3;
  public int JJTUNARYEXPR = 4;
  public int JJTDECIMAL = 5;


  public String[] jjtNodeName = {
    "Root",
    "Expr",
    "AddExpr",
    "MulExpr",
    "UnaryExpr",
    "Decimal",
  };
}
/* JavaCC - OriginalChecksum=90c8e91da1e0631ccc5dea03b6c5104c (do not edit this line) */
