/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package keisanki;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NUM = 1;
  /** RegularExpression Id. */
  int PLUSOP = 2;
  /** RegularExpression Id. */
  int MINUS = 3;
  /** RegularExpression Id. */
  int MULTIPLY = 4;
  /** RegularExpression Id. */
  int DIVIDE = 5;
  /** RegularExpression Id. */
  int CLEAR = 6;
  /** RegularExpression Id. */
  int EQOP = 7;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<NUM>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"C\"",
    "\"=\"",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
  };

}
